NotebookTherapyMVC/Areas/Manage/Controllers/ProductController.cs
namespace NotebookTherapyMVC.Areas.Manage.Controllers;
[Area("Manage")]
[Authorize(Roles = "Admin,SuperAdmin")]
public class ProductController : Controller
{
	private readonly IProductService _productService;
	private readonly ICategoryService _categoryService;
	private readonly ISizeService _sizeService;
	private readonly IBundleService _bundleService;
	private readonly IProductCollectionService _productCollectionService;
	private readonly IFavouriteService _favService;
	private readonly IAccountService _authService;
	private readonly IReviewService _reviewService;
	private readonly ICartItemService _cartItemService;
	private readonly IColorService _colorServoce;
	private readonly IMapper _mapper;

    public ProductController(IProductService service, IMapper mapper, ICategoryService categoryService, IProductCollectionService productCollectionService, ISizeService sizeService, IBundleService bundleService, IFavouriteService favService, IAccountService authService, IReviewService reviewService, ICartItemService cartItemService, IColorService colorServoce)
    {
        _productService = service;
        _mapper = mapper;
        _categoryService = categoryService;
        _productCollectionService = productCollectionService;
        _sizeService = sizeService;
        _bundleService = bundleService;
        _favService = favService;
        _authService = authService;
        _reviewService = reviewService;
        _cartItemService = cartItemService;
        _colorServoce = colorServoce;
    }

    public async Task<IActionResult> Index()
	{
        IDataResult<List<ProductGetDto>> result = await _productService.GetAllAsync(true, Includes.ProductIncludes);
		return View(result);
	}
	public async Task<IActionResult> Get(int id)
	{
		IDataResult<ProductGetDto> result = await _productService.GetByIdAsync(id,Includes.ProductIncludes);
		return PartialView("_getProductPartial", result);
	}
	[HttpGet]
	public async Task<IActionResult> Create()
	{
		await GetViewBags();
		return View();
	}

	[HttpPost]
	public async Task<IActionResult> Create(ProductPostDto dto)
	{
		if (!ModelState.IsValid)
		{
			await GetViewBags();
			return View(dto);
		}
		await _productService.CreateAsync(dto);
		return RedirectToAction(nameof(Index));
	}
	[HttpGet]
	public async Task<IActionResult> Update(int id)
	{
        IDataResult<ProductGetDto> result = await _productService.GetByIdAsync(id, "ProductImages", "Category", "ProductCollection", "ProductSizes.Size", "ProductBundles.Bundle");
		await GetViewBags();
		return View(_mapper.Map<ProductUpdateDto>(result.Data));
	}
	[HttpPost]
	public async Task<IActionResult> Update(ProductUpdateDto dto)
	{
		if (!ModelState.IsValid)
		{
			await GetViewBags();
			return View(dto);
		}
		await _productService.UpdateAsync(dto);
		return RedirectToAction(nameof(Index));
	}
	public async Task<IActionResult> Delete(int id)
	{
        IDataResult<ProductGetDto> result = await _productService.GetByIdAsync(id);
		if (result is null)
		{
			return RedirectToAction(nameof(Index), result);
		}
		await _productService.SoftDeleteByIdAsync(result.Data.Id);
		return RedirectToAction(nameof(Index));
	}

    public async Task<IActionResult> Recover(int id)
    {
        IDataResult<ProductGetDto> result = await _productService.GetByIdAsync(id);
        if (result is null)
        {
            return RedirectToAction(nameof(Index), result);
        }
        await _productService.RecoverByIdAsync(result.Data.Id);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> HardDelete(int id)
    {
        IDataResult<ProductGetDto> result = await _productService.GetByIdAsync(id);
        if (result is null)
        {
            return RedirectToAction(nameof(Index), result);
        }
        await _productService.HardDeleteByIdAsync(result.Data.Id);
        return RedirectToAction(nameof(Index));
    }
 //   #region Other Actions
 //   [HttpPost]
	//public async Task<IDataResult<FavouriteGetDto>> AddToFavourite(int id)
	//{
	//	FavouritePostDto dto = new()
	//	{
	//		ProductId = id,
	//		UserId = (await _authService.GetUserByClaims(User)).Data.Id
	//	};
	//	return await _favService.CreateAsync(dto);
	//}

	//[HttpPost]
	//public async Task<IResult> RemoveFromFavourite(int id)
	//{
	//	return await _favService.HardDeleteByIdAsync(id);
	//}

	//[HttpPost]
	//public async Task<IActionResult> WriteComment(ReviewPostDto dto)
	//{
	//	await _reviewService.CreateAsync(dto);
	//	return RedirectToAction("Get", "Product", new { id = dto.ProductId });
	//}

	//[HttpPost]
	//public async Task<IDataResult<CartItemGetDto>> AddItemToCart(int id)
	//{
	//	return await _cartItemService.CreateAsync(id, (await _authService.GetUserByClaims(User)).Data);
	//}

	//[HttpPost]
	//public async Task<IDataResult<CartItemGetDto>> RemoveItemFromCart(int id, bool deleteAll = false)
	//{
	//	return await _cartItemService.RemoveItemFromCartAsync(id, (await _authService.GetUserByClaims(User)).Data, deleteAll);
	//}
	//#endregion

	#region Private Methods
	private async Task GetViewBags()
	{
        IDataResult<List<CategoryGetDto>> categories = await _categoryService.GetAllAsync(false);
		IDataResult<List<ProductCollectionGetDto>> collections = await _productCollectionService.GetAllAsync(false);
		IDataResult<List<SizeGetDto>> sizes = await _sizeService.GetAllAsync(false);
		IDataResult<List<BundleGetDto>> bundles = await _bundleService.GetAllAsync(false);
		IDataResult<List<ColorGetDto>> colors = await _colorServoce.GetAllAsync(false);
        ViewBag.Categories = categories.Data.Select(c => new SelectListItem
		{
			Value = c.Id.ToString(),
			Text = c.Name
		});
		ViewBag.Collections = collections.Data.Select(c => new SelectListItem
		{
			Value = c.Id.ToString(),
			Text = c.Name
		});
		ViewBag.Sizes = sizes.Data.Select(c => new SelectListItem
		{
			Value = c.Id.ToString(),
			Text = c.Name
		});
		ViewBag.Bundles = bundles.Data.Select(c => new SelectListItem
		{
			Value = c.Id.ToString(),
			Text = c.Name
		});
		ViewBag.Colors = colors.Data.Select(c => new SelectListItem
        {
            Value = c.Id.ToString(),
            Text = c.Name
        });
    }
	#endregion
}

NotebookTherapyMVC/Controllers/BlogController.cs
namespace NotebookTherapyMVC.Controllers;

public class BlogController : Controller
{
    private readonly IBlogService _blogService;

    public BlogController(IBlogService blogService)
    {
        _blogService = blogService;
    }

    public async Task<IActionResult> Index()
    {
        IDataResult<List<BlogGetDto>> result = await _blogService.GetAllAsync(false);
        return View(result);
    }
    public async Task<IActionResult> Detail(int id)
    {
        IDataResult<BlogGetDto> result = await _blogService.GetByIdAsync(id);
        await _blogService.IncreaseViewCount(id);
        return View(result);
    }
    public async Task<IActionResult> GetPaginate(int page,int size)
    {
        IDataResult<List<BlogGetDto>> result = await _blogService.GetAllPaginateAsync(page,size,false);
        return PartialView("_bloglistPartial", result.Data);
    }
    public async Task<IActionResult> GetRelated()
    {
        IDataResult<List<BlogGetDto>> result = await _blogService.GetAllAsync(false);
        List<BlogGetDto> related = result.Data.OrderBy(x => Guid.NewGuid()).Take(3).ToList();
        return PartialView("_blogRelatedPartial", related);
    }
}

NotebookTherapyMVC/Controllers/CollectionController.cs
namespace NotebookTherapyMVC.Controllers;

public class CollectionController : Controller
{
    private readonly IProductCollectionService _productCollectionService;

    public CollectionController(IProductCollectionService productCollectionService)
    {
        _productCollectionService = productCollectionService;
    }

    public async Task<IActionResult> Detail(int id)
    {
        IDataResult<ProductCollectionGetDto> collection = await _productCollectionService.GetByIdAsync(id, Includes.ProductCollectionIncludes);
        return View(collection);
    }
}

NotebookTherapyMVC/Controllers/FAQController.cs
namespace NotebookTherapyMVC.Controllers
{
    public class FAQController : Controller
    {
        private readonly IFAQService _faqService;
        private readonly IFAQCategoryService _faqCategoryService;

        public FAQController(IFAQService faqService, IFAQCategoryService faqCategoryService)
        {
            _faqService = faqService;
            _faqCategoryService = faqCategoryService;
        }

        public async Task<IActionResult> Index()
        {
            IDataResult<List<FAQCategoryGetDto>> categoryResults = await _faqCategoryService.GetAllAsync(false,Includes.FAQCategoryIncludes);
            return View(categoryResults);
        }
    }
}

NotebookTherapyMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <partial name="_headPartial" />
    @RenderSection("BeforeMediaLinks",false)
    <link rel="stylesheet" href="~/assets/css/media.css">
    @RenderSection("AfterMediaLinks",false)
</head>

<body id="body">
    <partial name="_headerPartial" />

    <div class="overlap"></div>
    @RenderBody()
    <partial name="_footerPartial" />
    <partial name="_scriptsPartial" />
    @RenderSection("Scripts",false)
</body>
</html>

NotebookTherapyMVC/Views/Shared/_footerPartial.cshtml
<footer class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6 col-12 d-flex justify-content-center gap-3 icons">
                <i class="fa-brands fa-facebook-f"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-pinterest-p"></i>
            </div>
            <div class="col-md-3 col-sm-6 col-12">
                <h3 class="fs-4 fw-bold">Info</h3>
                <ul>
                    <li><a asp-action="Index" asp-controller="Blog">Blog</a></li>
                    <li><a asp-action="About" asp-controller="Home">About Us</a></li>
                    <li><a asp-action="Index" asp-controller="FAQ">Common Questions</a></li>
                    <li><a asp-action="Contact" asp-controller="Home">Contact us</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-12">
                <h3 class="fs-4 fw-bold">Shop</h3>
                <ul>
                    <li><a href="">New Additions</a></li>
                    <li><a href="">Top Selling</a></li>
                    <li><a href="">Notebooks</a></li>
                    <li><a href="">Bags</a></li>
                    <li><a href="">Pens</a></li>
                    <li><a href="">Pencil Cases</a></li>
                    <li><a href="">Stickers</a></li>
                    <li><a href="">Washi Tape</a></li>
                    <li><a href="">Gift Cards</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-6 col-12">
                <h3 class="fs-4 fw-bold">Join for special updates & discounts 👇</h3>
                <input type="email" placeholder="enter your email adress" class="mb-3">
                <input type="submit">
            </div>
        </div>
    </div>
</footer>

NotebookTherapyMVC/Views/Shared/_headPartial.cshtml
<title>@ViewData["Title"] - NotebookTherapy</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- === Favicon === -->
<link rel="icon" type="image/x-icon"
      href="https://cdn.shopify.com/s/files/1/2026/1775/files/NTfavicon_32x32.png?v=1613167164">
<!-- === Bootstrap CSS v5.2.3 === -->
<link rel="stylesheet" href="~/assets/libs/bootstrap-5.2.3-dist/css/bootstrap.min.css">
<!-- ==== Font Awesome Pro === -->
<link rel="stylesheet" href="~/Manage/assets/plugins/font-awesome/css/all.min.css">
<!-- ==== Custom Css === -->
<link rel="stylesheet" href="~/assets/css/header.css">
<link rel="stylesheet" href="~/assets/css/footer.css" />

NotebookTherapyMVC/Views/Shared/_headerPartial.cshtml
@inject ICategoryService _categoryService;
@inject IProductCollectionService _productCollectionService;
<header>
    <nav id="nav">
        <div class="header_top" id="navbar">
            <div class="logo">
                <a asp-action="Index" asp-controller="Home">
                    <img src="~/assets/images/logo.png" alt="">
                </a>
            </div>
            <div class="icons">
                <a asp-action="ShoppingCart" asp-controller="Account" class="me-2">
                    <i class="fa-regular fa-basket-shopping-simple fa-fade">
                    </i>
                    <span>Shopping Cart</span>
                </a>
                <a asp-controller="Account" asp-action="Favourite">
                    <i class="fa-regular fa-heart"></i>
                </a>
                <a asp-action="@(User.Identity.IsAuthenticated ? "Profile" : "Login")" asp-controller="Account" class="ms-2">
                    <i class="fa-regular fa-user"></i>
                </a>
            </div>
        </div>
        <div class="navbar_responsive">
            <div class="toggle_menu" id="toggle-menu">
                <i class="fa-regular fa-grid-2"></i>
            </div>
            <div class="logo">
                <a asp-action="Index" asp-controller="Home">
                    <img src="~/assets/images/logo.png" alt="">
                </a>
            </div>
            <div class="icons ">
                <a asp-action="ShoppingCart" asp-controller="Account">
                    <i class="fa-regular fa-basket-shopping-simple fa-fade">
                    </i>
                </a>
                <a asp-controller="Account" asp-action="Favourite">
                    <i class="fa-regular fa-heart"></i>
                </a>
                <a asp-action="@(User.Identity.IsAuthenticated ? "Profile" : "Login")" asp-controller="Account" class="ms-2">
                    <i class="fa-regular fa-user"></i>
                </a>
            </div>
        </div>
        <ul class="nav_list" id="nav-menu">
            <div class="close_menu" id="close-menu">
                <i class="fa-regular fa-xmark"></i>
            </div>
            <li class="nav_item drop_down">
                <div href="#" class="nav_link dropdown_link cursor-pointer d-inline">
                    All Categories
                    <i class="fa-solid fa-chevron-down dropdown_icon"></i>
                </div>
                <div class="megamenu">
                    <ul class="content flex-xl-row">
                        @if ((await _categoryService.GetAllAsync(false)).Success)
                        {
                            List<CategoryGetDto> categories = (await _categoryService.GetAllAsync(false)).Data;
                            @foreach (CategoryGetDto category in categories)
                            {
                                <li class="megamenu_item px-xl-3">
                                    <div class="megamenu_link">
                                        <a asp-controller="Product" asp-action="Index" asp-route-categoryId="@category.Id">@category.Name</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </li>
            <li class="nav_item">
                <a asp-controller="Product" asp-action="Index" class="nav_link">All Products</a>
            </li>
            <li class="nav_item">
                <a asp-controller="Product" asp-action="Index" asp-route-isTrending="true" class="nav_link">Trending</a>
            </li>
            <li class="nav_item">
                <a asp-controller="Home" asp-action="About" class="nav_link">About Us</a>
            </li>
            <li class="nav_item drop_down">
                <div href="#" class="nav_link dropdown_link cursor-pointer d-inline">
                    Seasonal Launches
                    <i class="fa-solid fa-chevron-down dropdown_icon"></i>
                </div>
                <div class="megamenu">
                    @{
                        List<ProductCollectionGetDto> collections = (await _productCollectionService.GetAllAsync(false)).Data;
                        int additional_content = collections.Count % 3;
                        int first_collection_content = collections.Count / 3;
                        int second_collection_content = collections.Count / 3;
                        if (additional_content > 0)
                        {
                            first_collection_content++;
                            if (additional_content == 2)
                            {
                                second_collection_content++;
                            }
                        }
                    }
                    <ul class="content">
                        @foreach (ProductCollectionGetDto collection in collections.Take(first_collection_content))
                        {
                            <li class="megamenu_item">
                                <div class="menu_icon">
                                    <span>@collection.CollectionIcon</span>
                                </div>
                                <div class="megamenu_link">
                                    <a asp-action="Detail" asp-controller="Collection" asp-route-id="@collection.Id">@collection.Name</a>
                                    <p>@collection.Description</p>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="content">
                        @foreach (ProductCollectionGetDto collection in collections.Skip(first_collection_content).Take(second_collection_content))
                        {
                            <li class="megamenu_item">
                                <div class="menu_icon">
                                    <span>@collection.CollectionIcon</span>
                                </div>
                                <div class="megamenu_link">
                                    <a asp-action="Detail" asp-controller="Collection" asp-route-id="@collection.Id">@collection.Name</a>
                                    <p>@collection.Description</p>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="content">
                        @foreach (ProductCollectionGetDto collection in collections.Skip(first_collection_content + second_collection_content).Take(collections.Count / 3))
                        {
                            <li class="megamenu_item">
                                <div class="menu_icon">
                                    <span>@collection.CollectionIcon</span>
                                </div>
                                <div class="megamenu_link">
                                    <a asp-action="Detail" asp-controller="Collection" asp-route-id="@collection.Id">@collection.Name</a>
                                    <p>@collection.Description</p>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </li>
            <li class="nav_item">
                <a asp-controller="Blog" asp-action="Index" class="nav_link">Blogs</a>
            </li>
            <li class="nav_item">
                <a asp-controller="Home" asp-action="Contact" class="nav_link">Contact Us</a>
            </li>
        </ul>
        <div class="icons icons_scroll">
            <a asp-action="ShoppingCart" asp-controller="Account">
                <i class="fa-regular fa-basket-shopping-simple fa-fade">
                </i>
            </a>
            <a asp-controller="Account" asp-action="Favourite">
                <i class="fa-regular fa-heart"></i>
            </a>
            <a asp-action="@(User.Identity.IsAuthenticated ? "Profile" : "Login")" asp-controller="Account" class="ms-2">
                <i class="fa-regular fa-user"></i>
            </a>
        </div>
    </nav>
</header>

NotebookTherapyMVC/Views/Shared/_scriptsPartial.cshtml
<!-- ==== Jquery === -->
<script src="~/assets/libs/jquery/jquery.min.js"></script>
<!-- === Bootstrap JavaScript Libraries === -->
<script src="~/assets/libs/bootstrap-5.2.3-dist/js/bootstrap.bundle.min.js"></script>
<!-- ==== Header === -->
<script src="~/assets/js/header.js"></script>